package com.example.cardiacrecorder.Model;

public class UserSignUpModel {

    public String email;
    public String userName;
    public String password;
    public String userKey;

    public UserSignUpModel() {
    }

    /**
     * This constructor is used to get email, userName, password and userKey at the time of retrieving data from database. It's also used to get data from user signUp page.
     * @param email
     * @param userName
     * @param password
     * @param userKey
     */

    public UserSignUpModel(String email, String userName, String password, String userKey) {
        this.email = email;
        this.userName = userName;
        this.password = password;
        this.userKey = userKey;
    }

    /**
     * This method gets the Email from the signUp page when a new user do signUp. It's also used to signIn an existing user.
     * @return The Email given by the user in the signUp or SignIn page.
     */

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method gets the UserName from the signUp page when a new user do signUp.
     * @return The UserName given by the user in the signUp page.
     */

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method gets the Password from the signUp page. It's also used to signIn an existing user.
     * @return The Password given by the user in the signUp page.
     */

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method gets the UserKey which is generated to use as the primary key of each user record.
     * @return The UserKey generated by the databaseReference pushKey() method in the sign up page.
     */

    public String getUserKey() {
        return userKey;
    }

    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }
}
